visit_list=['london','berlin','new york','singapore','montreal']
print(visit_list)
print(sorted(visit_list))
print(visit_list)
print(sorted(visit_list,reverse=True))
print(visit_list)
visit_list.reverse()
print(visit_list)
visit_list.reverse()
print(visit_list)
visit_list.sort()
print(visit_list)
visit_list.sort(reverse=True)
print(visit_list)
